
version: 2.1

jobs:
  publish-release:
    docker:
      - image: cimg/node:21.6.2
    steps: 
      - checkout
      - run: |
          export GITHUB_TOKEN=$GITHUB_TOKEN
          git config user.name "${GITHUB_USER}"
          git config user.email "${GITHUB_EMAIL}"
      - run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - run: npm install
      - run: npm run release

  publish-release-beta:
    docker:
      - image: cimg/node:21.6.2
    steps: 
      - checkout
      - run: |
          export GITHUB_TOKEN=$GITHUB_TOKEN
          git config user.name "${GITHUB_USER}"
          git config user.email "${GITHUB_EMAIL}"
          git branch --set-upstream-to origin/beta
      - run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - run: npm install
      - run: npm run release

workflows:
  version: 2.1
  publish_release:
    jobs:
      - publish-release:
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/
  publish_release_beta:
    jobs:
      - publish-release-beta:
          filters:
            branches:
              only: beta
            tags:
              ignore: /.*/
